name: cosmoflow

data:
  "name" : "cosmoUniverse_2019_05_4parE_tf_v2_mini"
  "url" : "https://portal.nersc.gov/project/dasrepo/cosmoflow-benchmark/cosmoUniverse_2019_05_4parE_tf_v2_mini.tar"
  "globus" : "https://app.globus.org/file-manager/collections/f59a3318-df18-11e9-b5de-0ef30f6b83a8/overview?back=endpoints"

model:
    "abstract": "CosmoFlow implementats a 3D convolutional neural network for N-body cosmological simulation."
    "description": "CosmoFlow is written in Python on top of TensorFlow with the Keras API and uses Horovod for distributed training."
    "name": "CosmoFlow"
    "homepage": "https://portal.nersc.gov/project/m3363/"
    "references":
    - "https://arxiv.org/abs/1808.04728"
    "git": "https://github.com/sparticlesteve/cosmoflow-benchmark.git"
    "forkts":
    - "git": "https://github.com/tokey-tahmid/cosmoflow-benchmark.git"
    "run":
      "cosmoUniverse_2019_05_4parE_tf_v2": "{python} train.py configs/cosmo.yaml"
